
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = "10000"
	#Energy per operation tick (Joules).
	osmiumCompressor = "5000"
	#Energy per operation tick (Joules).
	combiner = "1000000"
	#Energy per operation tick (Joules).
	crusher = "5000"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "5000"
	#Energy per operation tick (Joules).
	purificationChamber = "10000"
	#Energy per operation tick (Joules).
	energizedSmelter = "5000"
	#Energy per operation tick (Joules).
	digitalMiner = "400000"
	#Energy per operation tick (Joules).
	electricPump = "1000"
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "20000"
	#Energy per operation tick (Joules).
	oxidationChamber = "50000"
	#Energy per operation tick (Joules).
	chemicalInfuser = "20000"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "40000"
	#Energy per operation tick (Joules).
	precisionSawmill = "5000"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "50000"
	#Energy per operation tick (Joules).
	chemicalWasher = "20000"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "40000"
	#Energy per operation tick (Joules).
	seismicVibrator = "5000"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "5000"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "1000"
	#Energy per operation tick (Joules).
	laser = "100000"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "10000"
	#Energy per operation tick (Joules).
	modificationStation = "10000"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "200000"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "2000"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "2000000"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "500000"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "1000"
		#Flat additional cost for interdimensional teleportation.
		teleporterDimensionPenalty = "500000"

