
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	enrichmentChamber = "100000"
	#Base energy storage (Joules).
	osmiumCompressor = "50000"
	#Base energy storage (Joules).
	combiner = "10000000"
	#Base energy storage (Joules).
	crusher = "50000"
	#Base energy storage (Joules).
	metallurgicInfuser = "50000"
	#Base energy storage (Joules).
	purificationChamber = "100000"
	#Base energy storage (Joules).
	energizedSmelter = "50000"
	#Base energy storage (Joules).
	digitalMiner = "500000000"
	#Base energy storage (Joules).
	electricPump = "10000"
	#Base energy storage (Joules).
	chargePad = "5000000"
	#Base energy storage (Joules).
	rotaryCondensentrator = "200000"
	#Base energy storage (Joules).
	oxidationChamber = "500000"
	#Base energy storage (Joules).
	chemicalInfuser = "200000"
	#Base energy storage (Joules).
	chemicalInjectionChamber = "400000"
	#Base energy storage (Joules).
	electrolyticSeparator = "160000"
	#Base energy storage (Joules).
	precisionSawmill = "50000"
	#Base energy storage (Joules).
	chemicalDissolutionChamber = "500000"
	#Base energy storage (Joules).
	chemicalWasher = "200000"
	#Base energy storage (Joules).
	chemicalCrystallizer = "400000"
	#Base energy storage (Joules).
	seismicVibrator = "20000"
	#Base energy storage (Joules).
	pressurizedReactionBase = "50000"
	#Base energy storage (Joules).
	fluidicPlenisher = "10000"
	#Base energy storage (Joules).
	laser = "1000000"
	#Base energy storage (Joules).
	formulaicAssemblicator = "40000"
	#Base energy storage (Joules).
	teleporter = "5000000"
	#Base energy storage (Joules).
	modificationStation = "40000"
	#Base energy storage (Joules).
	isotopicCentrifuge = "2000000"
	#Base energy storage (Joules).
	nutritionalLiquifier = "40000"
	#Base energy storage (Joules). Also defines max process rate.
	antiprotonicNucleosynthesizer = "20000000"
	#Base energy storage (Joules). Also defines max output rate.
	spsPort = "1000000000"

